const about = {
  about: {
    meta: {
      title: 'Syscoin SentryNodes - About Syscoin SentryNodes',
      keywords: 'Syscoin, SentryNodes, Blockchain, Crypto, Blockmarket, Coins, Bitcoin, Cryptocurrency, Rewards',
      description: 'Sysnode.info provides Syscoin Sentry Node Operators the tools to maximise the most from their SentryNodes!',
    },
    title: 'Learn About Syscoin SentryNodes',
    masternodes: {
      question: {
        p1: 'What sets',
        p2: 'Syscoin SentryNodes apart?',
      },
      featureList: {
        f1: 'Z-DAG Protocol’s instant Asset transfer',
        f2: 'Scalability',
        f3: 'Facilitation of future Syscoin features and services',
        f4: 'Seniority benefits to masternode operators',
      },
      description: {
        d1: 'Syscoin SentryNodes protect the blockchain from network attacks, in the same vein as traditional proof of stake algorithms. It’s often expensive to accumulate enough of a currency to create a masternode. This expense helps keep the network decentralised, as it would take an ungodly amount of money to purchase enough currency to have a monopoly on its nodes.',
        d2: 'The cost of operating a Sentry Node also keeps operators honest. Unlike Bitcoin miners, who may switch from one coin on its blockchain to the next based on profitability, operators are incentivised to properly maintain and upkeep their Syscoin SentryNodes. The exorbitant initial investment serves as collateral, whereby if operators want their investment to pay off, they have to play by the blockchain’s rules. Between the high operation costs and promising return on investment, it’s in an operator’s best interest to operate his/her node properly and without any malicious intent.',
      }
    },
    governance: {
      title: 'Decentralized Governance',
      question: 'How does Decentralized Governance work?',
      description:{
        d1: 'Each month a pot of governance funding is generated by the Syscoin blockchain ‘superblock’. Any individual or group can submit a proposal to receive some of these funds. Sentry Node owners vote on the proposals using voting technology embedded in the Syscoin blockchain (accessible via the Qt wallet or syshub.org). At the end of the monthly voting period funds are distributed to the proposals with the greatest number of positive votes. Successful projects tend to be those that support and advance Syscoin Platform, such as marketing initiatives and application development.',
        d2: 'Syscoin have implemented a % decline schedule — starting the first month with 1,500,000 SYS and ending on the 24th month with 196,708 SYS. After that period, the superblock starts with 151,767 SYS a month and will decline 5% every year.',
      },
    },
    rewards: {
      title: 'Rewards',
      question: 'How does Decentralized Governance work?',
      description: {
        d1: '75% of each regular block reward is distributed to Sentry Node operators as an incentive to continue running the node. Each payout amounts to roughly 25 SYS, though this will increase over time due to the Seniority Benefits mechanism. The likelihood of a Sentry Node receiving a payout is inversely proportional to the total number of SentryNodes on the network. At the time of writing, a Sentry Node is likely to receive a 53 SYS reward roughly once every 4-5 days.',
        d2: 'As a seniority benefit, Sentry Node operators receive a 35% bonus to their base reward after one year, and a 100% bonus after 2.5 years. This benefit is paid only if the collateral for an active Sentry Node is kept locked at the same address for the entire qualification period.',
      },
    },
    seniority: {
      title: 'Sentry Node Seniority Explained',
      description: 'It’s been noted that Syscoin price fluctuations may in turn cause fluctuations in the number of masternodes running on the network. To mitigate this and incentivise nodes to provide services consistently for long periods of time, we have introduced a seniority mechanism that increases ROI for long-term nodes.',
      seniority: {
        s1: {
          title: 'There are two levels of Seniority',
          d1: '1 year – 35% increase of base rate',
          d2: '2.5 years - 100% increase of base rate',
        },
        s2: {
          title: 'Syscoin Average Block is 60 Seconds',
          d1: 'Therefore;',
          d2: '1 Month = 43,800 Blocks',
          d3: '1 Year Seniority = 526,600 Blocks',
          d4: '2.5 Year Seniority = 1,314,000 Blocks',
        },
        s3: {
          title: 'Calculating 1 Year Seniority',
          d1: 'You sent your 100,000 Syscoin at Block Height 1000.',
          d2: '525,600 + 1,000 = 526,600.',
          d3: '526,600 Block Height = Your first increase in Seniority.',
        },
        s4: {
          title: 'Calculating 2 Year Seniority',
          d1: 'You sent your 100,000 Syscoin at Block Height 1000.',
          d2: '1,314,000 + 1000 = 1,315,000',
          d3: '1,314,000 Block Height = Your second increase in Seniority.',
        },
      },
      note: { // check /About for more context on how to translate these..
        n1: {
          p1: 'Please note that Seniority is based purely on the',
          p2: 'Transaction Block Height',
          p3: 'The',
          p4: 'ONLY',
          p5: 'thing that will affect your Seniority is if you MOVE YOUR 100,000 Syscoin, which creates a new transaction, giving you a new Block Height.',
        },
        n2: 'Stopping your Syscoin Sentry Node, restarting your server, closing QT, upgrading SentryNodes, Initialising your Sentry Node, changing your IP address, and anything you can possibly think of does not effect your Seniority.',
      },
    },
    requirements: {
      title: 'Requirements to Setup a Syscoin Sentry Node',
      requirement: {
        r1: '100,000 Syscoin',
        r2: 'Linux OS — Ubuntu 20.04 LTS (Focal Fossa) preferred.',
        r3: 'KVM or OpenVZ (KVM preferred) ',
        r4: '64-bit CPU — 2 Cores (4 Cores preferred)',
        r5: '4GB RAM (real) minimum (8GB RAM preferred); 4GB swap (if less than 8gb real RAM) Will need to use SSD if using Swap',
        r6: '80GB+ SSD Hard Disk (100GB+ Recommended)',
        r7: 'Static IP Address',
      },
    },
  },
}
export default about;