export default {
    governance: {
      heading: 'Syscoin Governance',
      title: 'Syscoin Masternodes - Governance',
      keywords: 'Syscoin, Masternodes, Blockchain, Crypto, DeFi, Governance, Bitcoin, Cryptocurrency, Ethereum',
      description: 'Sysnode.info provides Syscoin Masternode Operators the tools to maximise the most from their Masternodes!',
      par1: 'Each month a pot of governance funding is generated by the Syscoin blockchain ‘superblock’. Any individual or group can submit a proposal to receive some of these funds. Masternode owners vote on the proposals using voting technology embedded in the Syscoin blockchain (accessible via the Qt wallet or syshub.org). At the end of the monthly voting period funds are distributed to the proposals with the greatest number of positive votes. Successful projects tend to be those that support and advance Syscoin Platform, such as marketing initiatives and application development.',
      par2: 'Syscoin have implemented a % decline schedule — starting the first month with 1,500,000 SYS and ending on the 24th month with 196,708 SYS. After that period, the superblock starts with 151,767 SYS a month and will decline 5% every year.',
    },
  }
  