export default {
  // App States
  APP_USER_LOGIN: 'APP_USER_LOGIN',
  APP_USER_LOGOUT: 'APP_USER_LOGOUT',
  APP_LOADING_GLOBAL: 'APP_LOADING_GLOBAL',
  APP_PAGE_SHOW: 'APP_PAGE_SHOW',
  APP_CHAT_TOGGLE: 'APP_CHAT_TOGGLE',
  APP_MENU_TOGGLE: 'APP_MENU_TOGGLE',
  APP_PLATFORM_GET: 'APP_PLATFORM_GET',
  APP_PROPOSAL_CONTAINER: 'APP_PROPOSAL_CONTAINER',
  APP_PROPOSAL_SHOW: 'APP_PROPOSAL_SHOW',

  // Sys Stats states
  SYS_STATS_USER_GET: 'SYS_STATS_USER_GET',
  SYS_STATS_PRICE_GET: 'SYS_STATS_PRICE_GET',
  SYS_STATS_TMN_GET: 'SYS_STATS_TMN_GET',
  SYS_STATS_RMN_GET: 'SYS_STATS_RMN_GET',

  //SYS Proposals
  SYS_PROPOSALS_GET: 'SYS_PROPOSALS_GET',
  SYS_PROPOSALS_CHECK: 'SYS_PROPOSALS_CHECK',
  SYS_PROPOSALS_PREPARE: 'SYS_PROPOSALS_PREPARE',
  SYS_PROPOSALS_SUBMIT: 'SYS_PROPOSALS_SUBMIT',
  SYS_PROPOSAL_VOTE: 'SYS_PROPOSAL_VOTE',

  //2FA
  SET_AUTH: 'SET_AUTH',

  // MEDIUM Connect
  MEDIUM_POSTS_GET: 'MEDIUM_POSTS_GET'
};
