export default {
  // App States
  APP_LOGIN_USER: 'APP_LOGIN_USER',
  APP_LOGOUT_USER: 'APP_LOGOUT_USER',
  APP_LOADING_GLOBAL: 'APP_LOADING_GLOBAL',
  APP_PAGE_SHOW: 'APP_PAGE_SHOW',

  // Sys Stats states
  SYS_STATS_SET: 'SYS_STATS_SET',
};
