export default {
  // App States
  APP_USER_LOGIN: 'APP_USER_LOGIN',
  APP_USER_LOGOUT: 'APP_USER_LOGOUT',
  APP_LOADING_GLOBAL: 'APP_LOADING_GLOBAL',
  APP_PAGE_SHOW: 'APP_PAGE_SHOW',
  APP_CHAT_TOGGLE: 'APP_CHAT_TOGGLE',

  // Sys Stats states
  SYS_STATS_GET: 'SYS_STATS_GET',

  //SYS Proposals
  SYS_PROPOSALS_GET: 'SYS_PROPOSALS_GET',
  SYS_PROPOSALS_CHECK: 'SYS_PROPOSALS_CHECK',
  SYS_PROPOSALS_PREPARE: 'SYS_PROPOSALS_PREPARE',
  SYS_PROPOSALS_SUBMIT: 'SYS_PROPOSALS_SUBMIT',

  //2FA
  SET_AUTH: 'SET_AUTH',
};
