export default {
  // App States
  APP_USER_LOGIN: 'APP_USER_LOGIN',
  APP_USER_LOGOUT: 'APP_USER_LOGOUT',
  APP_LOADING_GLOBAL: 'APP_LOADING_GLOBAL',
  APP_PAGE_SHOW: 'APP_PAGE_SHOW',
  APP_CHAT_TOGGLE: 'APP_CHAT_TOGGLE',

  // Sys Stats states
  SYS_STATS_SET: 'SYS_STATS_SET',

  //SYS Proposals
  SYS_PROPOSALS_GET: 'SYS_PROPOSALS_GET',
};
